# Generated by Django 3.1.7 on 2021-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRevendeurApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantityinstock',
            options={'ordering': ('tigId', 'quantityInStock')},
        ),
        migrations.AddField(
            model_name='quantityinstock',
            name='tigId',
            field=models.IntegerField(default='-1'),
        ),
    ]
